//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivoDiplomado
    {
        public string idArchivo { get; set; }
        public string DescripciónArchivo { get; set; }
        public string Archivo { get; set; }
        public Nullable<int> MaxDescargas { get; set; }
        public int idDiplomado { get; set; }
    
        public virtual catDiplomado catDiplomado { get; set; }
    }
}
