//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catCondiciones
    {
        public int idCondicion { get; set; }
        public string NombreCondicion { get; set; }
        public string DescripcionCondicion { get; set; }
        public Nullable<int> idConvocatoria { get; set; }
    
        public virtual catConvocatoria catConvocatoria { get; set; }
    }
}
