//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catDepartamento
    {
        public catDepartamento()
        {
            this.catMensajes = new HashSet<catMensajes>();
            this.catVuMotivos = new HashSet<catVuMotivos>();
        }
    
        public int idDepartamento { get; set; }
        public string nomDepartamento { get; set; }
        public string ResponsableId { get; set; }
        public string Proposito { get; set; }
        public Nullable<int> nivel { get; set; }
    
        public virtual ICollection<catMensajes> catMensajes { get; set; }
        public virtual ICollection<catVuMotivos> catVuMotivos { get; set; }
    }
}
