//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catEncuesta
    {
        public int idEncuesta { get; set; }
        public Nullable<System.DateTime> fechaEncuesta { get; set; }
        public Nullable<System.DateTime> fechaEncuestaFin { get; set; }
        public string descripciónEncuesta { get; set; }
        public string idAutorEncuesta { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> Clicks { get; set; }
        public string UrlEncuesta { get; set; }
        public string tituloEncuesta { get; set; }
    }
}
