//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catInformacion
    {
        public string idDocumento { get; set; }
        public string url { get; set; }
        public string archivo { get; set; }
        public Nullable<int> idSeccion { get; set; }
        public string Descripcion { get; set; }
        public string tipoArchivo { get; set; }
        public string tamañoArchivo { get; set; }
        public string descripcionCorta { get; set; }
    
        public virtual catSeccion catSeccion { get; set; }
    }
}
