//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catMensajes
    {
        public string idCorreo { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string InistitucionNombre { get; set; }
        public string Telefono { get; set; }
        public string Departamento { get; set; }
        public string Correo { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<int> idDepartamentoCanalizacion { get; set; }
    
        public virtual catDepartamento catDepartamento { get; set; }
    }
}
