//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catModulos
    {
        public int idModulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> idTaller { get; set; }
    
        public virtual catTalleres catTalleres { get; set; }
    }
}
