//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catProyecto
    {
        public int idProyecto { get; set; }
        public string ProyectoTitulo { get; set; }
        public string ProyectoDescripcion { get; set; }
        public string ProyectoUrlSlug { get; set; }
        public string ProyectoArchivo { get; set; }
        public string autorId { get; set; }
        public Nullable<System.DateTime> ProyectoFecha { get; set; }
        public string ProyectoEstado { get; set; }
    }
}
