//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catSlider
    {
        public string SliderDescripcion { get; set; }
        public string SliderImagen { get; set; }
        public string SliderUrlSlug { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public Nullable<System.DateTime> SliderInicio { get; set; }
        public Nullable<System.DateTime> SliderFin { get; set; }
        public Nullable<int> Destino { get; set; }
        public string idNoticia { get; set; }
        public int idSlider { get; set; }
    
        public virtual catNoticia catNoticia { get; set; }
    }
}
