//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catSeccion
    {
        public catSeccion()
        {
            this.catInformacion = new HashSet<catInformacion>();
        }
    
        public int idSeccion { get; set; }
        public string SeccionNombre { get; set; }
        public Nullable<int> tipoSeccion { get; set; }
        public string idCreador { get; set; }
        public Nullable<int> idTipoCliente { get; set; }
    
        public virtual ICollection<catInformacion> catInformacion { get; set; }
        public virtual TiposClientes TiposClientes { get; set; }
    }
}
