//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class catVuMotivos
    {
        public int idMotivo { get; set; }
        public Nullable<int> idDepartamento { get; set; }
        public string descMotivo { get; set; }
    
        public virtual catDepartamento catDepartamento { get; set; }
    }
}
