//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentario
    {
        public int idComentario { get; set; }
        public string contenido { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string autor { get; set; }
        public string email { get; set; }
        public Nullable<int> idPost { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
