//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracionSitio
    {
        public configuracionSitio()
        {
            this.configuracionSitioDocumentos = new HashSet<configuracionSitioDocumentos>();
        }
    
        public int idPagina { get; set; }
        public string NombreSitioLargo { get; set; }
        public string NombreSitioCorto { get; set; }
        public string antecedentes { get; set; }
        public string misionvision { get; set; }
        public string ubicacion { get; set; }
        public string imagenFrontal { get; set; }
        public string imagenOrganigrama { get; set; }
        public Nullable<bool> SitioDisponible { get; set; }
        public string ContactoLinea1 { get; set; }
        public string ContactoLinea2 { get; set; }
        public string ContactoLinea3 { get; set; }
        public Nullable<decimal> Telefono { get; set; }
        public Nullable<int> Extencion { get; set; }
        public string NombreConfiguracion { get; set; }
    
        public virtual ICollection<configuracionSitioDocumentos> configuracionSitioDocumentos { get; set; }
    }
}
