//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracionSitioDocumentos
    {
        public int idDoc { get; set; }
        public string descripcion { get; set; }
        public string urlArchivo { get; set; }
        public Nullable<int> idSitio { get; set; }
    
        public virtual configuracionSitio configuracionSitio { get; set; }
    }
}
