//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class galeriaNoticias
    {
        public string idImagen { get; set; }
        public string idNoticia { get; set; }
        public string rutaArchivo { get; set; }
        public string rutaThumbnail { get; set; }
    
        public virtual catNoticia catNoticia { get; set; }
    }
}
