//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdCinotamVersionOTCEntities : DbContext
    {
        public bdCinotamVersionOTCEntities()
            : base("name=bdCinotamVersionOTCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<archivoDiplomado> archivoDiplomado { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<catCategoriasPost> catCategoriasPost { get; set; }
        public virtual DbSet<catCondiciones> catCondiciones { get; set; }
        public virtual DbSet<catConvocatoria> catConvocatoria { get; set; }
        public virtual DbSet<catDepartamento> catDepartamento { get; set; }
        public virtual DbSet<catDiplomado> catDiplomado { get; set; }
        public virtual DbSet<catEncuesta> catEncuesta { get; set; }
        public virtual DbSet<catExpositorExterno> catExpositorExterno { get; set; }
        public virtual DbSet<catInformacion> catInformacion { get; set; }
        public virtual DbSet<catMensajes> catMensajes { get; set; }
        public virtual DbSet<catModulos> catModulos { get; set; }
        public virtual DbSet<catNoticia> catNoticia { get; set; }
        public virtual DbSet<catProyecto> catProyecto { get; set; }
        public virtual DbSet<catRequisitos> catRequisitos { get; set; }
        public virtual DbSet<catSeccion> catSeccion { get; set; }
        public virtual DbSet<catSlider> catSlider { get; set; }
        public virtual DbSet<catTalleres> catTalleres { get; set; }
        public virtual DbSet<catVuMotivos> catVuMotivos { get; set; }
        public virtual DbSet<comentario> comentario { get; set; }
        public virtual DbSet<configuracionSitio> configuracionSitio { get; set; }
        public virtual DbSet<configuracionSitioDocumentos> configuracionSitioDocumentos { get; set; }
        public virtual DbSet<contactoConvocatoria> contactoConvocatoria { get; set; }
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<datosUsuario> datosUsuario { get; set; }
        public virtual DbSet<galeriaNoticias> galeriaNoticias { get; set; }
        public virtual DbSet<Hash> Hash { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobParameter> JobParameter { get; set; }
        public virtual DbSet<JobQueue> JobQueue { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Registro> Registro { get; set; }
        public virtual DbSet<Schema> Schema { get; set; }
        public virtual DbSet<Server> Server { get; set; }
        public virtual DbSet<Set> Set { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TiposClientes> TiposClientes { get; set; }
    }
}
