//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int idPermiso { get; set; }
        public string idEmpleado { get; set; }
        public Nullable<System.DateTime> horaSalida { get; set; }
        public Nullable<System.DateTime> horaRegreso { get; set; }
        public string idAdministrador { get; set; }
        public string razon { get; set; }
        public Nullable<bool> autorizado { get; set; }
        public string observaciones { get; set; }
        public string ipPeticion { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    }
}
