//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public string FolioRegistro { get; set; }
        public string NombreCompleto { get; set; }
        public string Email { get; set; }
        public string RazonSocial { get; set; }
        public string Telefono { get; set; }
        public string Localidad { get; set; }
        public string DescripcionEmpresa { get; set; }
        public Nullable<int> idConvocatoria { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual catConvocatoria catConvocatoria { get; set; }
    }
}
